name: 自动双源无损强行合并-备用线

on:
  schedule:
    # 🎯 避开整点塞车，北京时间 08:43 和 20:43 高效跑数
    - cron: '43 0,12 * * *'
  workflow_dispatch: 

permissions: write-all

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Fetch target files
      run: |
        mkdir -p datas
        curl -L "https://cnb.cool/fish2018/xs/-/git/raw/main/api.json" -o datas/cnb.json
        curl -L "https://raw.githubusercontent.com/FGBLH/HKL/refs/heads/main/ok%E6%B5%B7%E8%B1%9A.json" -o datas/haitun.json

    - name: Text Merge JSON
      env:
        # 传递授权凭证给 Python 内置网络驱动，实现闪电通知
        TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        python modify_config.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global core.quotepath false
        
        git add datas/
        if ! git diff --cached --exit-code --quiet; then
          git commit -m "自动同步最新绿色去敏感纯净版合并接口: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "文件内容无变动，无需更新提交，优雅退出。"
        fi
